### ISSUE TITLE
Slash Command not working as intended: Award item without auction while being in an active raid and awarding linked item to targeted player for DKP value.

### ISSUE THREAD

**Issue by Elyiale** [ClassicLootManager/ClassicLootManager#451] opened 2023-01-18 07:44 UTC
In the past, I was able to use a slash command to award items to a targeted player for a specific DKP value without an auction. Example: /clm award [Hearthstone]/15. 

Now, instead of immediately awarding the item, this slash command brings up other option windows (choose player, DKP value, confirmation), which is slowing the process down significantly. 

**AddOn and Game Version:**
 - v3.0.0 (but this started happening several updates ago)
 - 3.4.1

**Comment by lantisnt** [comment] 2023-01-18 08:04
Working as intended. Moving this to an improvement taks to reeanble also non-gui way in parallel

**Closed** 2023-01-18 09:39 UTC
Labels: feature, Priority::Low
